image:
  repository: haroldo89/python-app
  tag: "2"
replicaCount: 1
service:
  nodePort: 32400
  port: 80
  targetPort: 5000
  type: NodePort
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"